name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup nodejs enviroment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - run: cd client; npm ci
      - run: cd client; npm run build
      
      - name: copy to production branch
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: client/dist
          src_branch: production
          dst_path: /public/
          dst_owner: MdNaina
          dst_repo_name: gitdemo
