name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup nodejs enviroment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - run: |
          cd client
          npm ci
          npm run build && cp -r ./dist ../server/public
          git config user.name "github-actions[bot]"
          git config user.email "github.com"
          git add ../server/public
          git commit -m "build by github action"
      
