name: Build and Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup nodejs enviroment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Building
        run: |
          cd client
          pwd
          npm ci
          rm -r ./dist || echo "no old build folder was found"
          rm -r ../server/public/* || echo "no api public build folder was found"
          npm run build && cp -rf ./dist/* ../server/public
          git config user.name "github-actions[bot]"
          git config user.email "github.com"
          pwd
          git add ../server/public
          git status
          git commit -m "build by github action"
          git push origin master
          echo "Complete"
          
      - name: copy to production branch
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /server/.
          src_branch: master
          dst_branch: production
          dst_path: /
          dst_owner: MdNaina
          dst_repo_name: gitdemo
      
